name: Create Automated Pre-release

on:
  workflow_run:
    workflows: ["Automated Builds"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  create-prerelease:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest commit info
        id: commit_info
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          changelog=$(git log --pretty=format:"- %s (%h)" $(git describe --tags --abbrev=0)..HEAD)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$changelog" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Download artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: ./artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Prepare release assets
        run: |
          mkdir -p release_assets
          for os in ubuntu-20.04 windows macos-universal; do
            find ./artifacts -name "*$os*.zip" -exec cp {} ./release_assets/ \;
          done

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: "latest-build"
          name: "Latest Pre-release Build"
          body: |
            This is an automated pre-release based on the latest commit:

            Commit Message: ${{ steps.commit_info.outputs.message }}
            Commit SHA: ${{ steps.commit_info.outputs.sha }}

            [Full Changelog](https://github.com/OseMine/variable-synth/commits/Build)

            Changes since last release:
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./release_assets/*"
          allowUpdates: true
          replacesArtifacts: true
