name: Create Pre-release

on:
  workflow_run:
    workflows: ["Automated Builds"]
    types:
      - completed

jobs:
  create_release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: ./downloads

      - name: Generate Release Name
        id: release_info
        run: |
          COMMIT_HASH="${{ github.event.workflow_run.head_commit.id }}"
          COMMIT_MESSAGE="${{ github.event.workflow_run.head_commit.message }}"
          RELEASE_NAME="Build from commit $COMMIT_HASH - $COMMIT_MESSAGE"
          
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV

      - name: Create or Update GitHub Pre-release
        uses: actions/create-release@v1
        with:
          tag_name: Pre-Release
          release_name: ${{ env.RELEASE_NAME }}
          body: |
            This is an automated pre-release based on the latest commit:
            [Full Changelog](https://github.com/OseMine/variable-filter/commits/Build)
            
            ### Commit Summary
            ${{ github.event.workflow_run.head_commit.message }}
          prerelease: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts as Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./downloads
          asset_name: "Build_Pre-Release.zip"
          asset_content_type: application/zip
